### ISSUE TITLE
Einarbeitung Spring Data Neo4j

### ISSUE THREAD

**Issue by Danmyrer** [Jacinto-S/VeranstaltungsTauschboerse#2]
Blockiert: DB Implementierung

Einarbeitung nach https://neo4j.com/docs/getting-started/languages-guides/java/spring-data-neo4j/

**Comment by nicok1** [comment]
Schaut mal in den html-beispiel Branch rein. Ich habe ein funktionierendes Beispiel mit Spring Data Neo4j erstellt und gepusht. In dem Beispiel fehlt natürlich noch das Ausführen selbst geschriebener spezieller Queries (z.B. für den Matching Algorithmus). 

Schaut euch geg. für euren Bedarf die application.properties an und passt sie an. 

Bisherige Erkenntnis: 
- Spring Boot kann mit der neusten Version von neo4j interagieren
- Die Integration mit Spring Data funktioniert wunderbar

Funfact: 
Laut Wikipedia sitzt der Gründer von Spring Boot im Aufsichtsrat der Firma hinter Neo4j :)
