### ISSUE TITLE
Import von Veranstaltungsterminen über ICS Datei

### ISSUE THREAD

**Issue by nicok1** [Jacinto-S/VeranstaltungsTauschboerse#4]
Mir ist aufgefallen, dass AOR die Funktion "ICS Datei" herunterladen anbietet. Das ist ein halbwegs standardisiertes Format, welches es super einfach ermöglichen würde, ohne großen administrativen Aufwand unsere Webseite betreiben zu können. Leute würden die Datei auf unserer Seite hochladen können. 

**Das hätte mehrere Vorteile:**
- Die Nutzer legen ihre Einträge für Ihren Studiengang selbst an, kein administrativer Eingriff notwendig
- Fehler beim Anlegen sind ausgeschlossen -> Der Matching Alg. kommt damit zurecht
- Die Übertragung der Termine in unsere Anwendung wird stark vereinfacht
- Personalisierung der Anwendung ist besser möglich (Wir können z.B. Termine während Vorlesungen oder anderer Praktika ausblenden)

Mein Vorschlag wäre, Nutzer bei Anmeldung dazu zu zwingen, ihren Studiengang anzugeben. Danach werden sie dazu gedrängt (oder gezwungen), Ihre ICS Datei hochzuladen. 

Wir könnten das Hochladen einer solchen Datei für einen einheitlichen Workflow erzwingen, oder es als optionalen Schritt anbieten. 
Was haltet ihr davon?

Ich persönlich würde mich für den Zwang aussprechen. 
Die Nutzer könnten über einen Button folgenden Link öffnen: https://aor.cs.hs-rm.de/plans.ics?user_plan=true
Sind sie angemeldet, so wird die Datei direkt heruntergeladen. Ansonsten wird sie nach erfolgreicher Anmeldung heruntergeladen. 

Danach fordern wir die Nutzer dazu auf, die Datei hochzuladen. Die Datei wird dann auf dem Server überprüft und bei Erfolg angewandt. 

Außer dem Dozenten können wir alle Infos zu einer Veranstaltung aus der Datei extrahieren. 
Hier ein Beispiel für das BS Praktikum:
![image](https://github.com/Jacinto-S/VeranstaltungsTauschboerse/assets/34523672/481b83a6-d7ee-4436-8af6-2316236caee8)

**Comment by Jacinto-S** [comment]
Also die Idee mit der Datei ist gut, das mit dem Zwang müssen wir nochmal besprechen ...

**Comment by Danmyrer** [comment]
Zwang ist das falsche Wort wenn wir so oder so keinen anderen Weg anbieten. 
Finde die Idee aber sehr gut, weil wir so serverseitig der Authentizität der Uploads halbwegs vertrauen können und somit nen einfachen workflow haben.

- User verifiziert sich mit HSRM-Mail
- User lädt seinen Stundenplan auf den Thin-Client
- User wählt seine Tauschangebote aus
- Angebote werden mit Modulen auf den Server/ die DB hochgeladen 

DB / Backend seitig sehe ich da kein Problem

**Comment by Danmyrer** [comment]
Ein Problem der ICS-Dateien ist, dass diese nur für die Studiengänge existieren, die auch AOR benutzen. Wenn in den nächsten Semestern AOR abgeschafft wird oder ein anderer Studiengang das Tool nutzen möchte, müssten wir das Frontend anpassen.

Meiner Meinung nach können wir erstmal das ganze mit ICS machen und ggf. später weiter implementieren, sofern wir Zeit und Lust haben.

**Comment by nicok1** [comment]
+1

Vergessen wir das mit dem Zwang. Nennen wir es zielgerichtete Nutzerführung ;)

Wir könnten für den Backlog oder den "Nice To Have" Fall noch einen alternativen Flow vorsehen. Die Methode mit der Kalenderdatei würde die händische Pflege komplett obsolet machen und wäre eine zumutbare Aufgabe für den User. Stand jetzt ist unsere Plattform ohnehin nur für die Nutzer des AOR Systems vorgesehen.

**Comment by Jacinto-S** [comment]
Jo, ich würde die CSV Datei optional annehmen und dann werden die Termine Automatisch eingepflegt sodass andere die optional schon vorauswählen können. Wenn man das einigermaßen gescheit modular implementiert kann man das ziemlich cool machen. Ich schau Mal das ich nachher oder morgen ne mögliche Planung davon skizziere.
