### ISSUE TITLE
Mailversand

### ISSUE THREAD

**Issue by nicok1** [Jacinto-S/VeranstaltungsTauschboerse#5]
**Beschreibung:**
Der Versand von E-Mails stellt uns vor mehrere Herausforderungen:

1. **Komplexität**: Die Einrichtung eines eigenen Mailservers ist nicht trivial und kann sehr komplex sein.
2. **Wartung**: Ein eigener Mailserver erfordert kontinuierliche Wartung und Überwachung.
3. **Reputation**: Selbst wenn der Mailserver ordnungsgemäß funktioniert, kann es schwierig sein, eine gute Reputation aufzubauen, wodurch die Gefahr besteht, dass unsere E-Mails als Spam markiert werden oder nicht zugestellt werden. 

**Verwendungszweck des Mailversands:**
1. **Authentifizierung**: Da es kein Passwort für den Zugriff auf unsere Plattform gibt, erhalten die Nutzer über ihre Hochschul-E-Mail-Adresse einen Link für den Login bzw. die Registrierung. Dieser Link enthält einen Token zur Verifizierung ihrer Identität.
2. **Benachrichtigung bei erfolgreicher Vermittlung**: Die Nutzer müssen informiert werden, wenn eine erfolgreiche Vermittlung stattgefunden hat, da sie nicht regelmäßig auf der Plattform nachsehen werden. Diese Benachrichtigung kann evtl. optional auch an ihre private E-Mail-Adresse gesendet werden, die nicht mit anderen geteilt wird.

Die Mails würden von unserem Backendsystem versendet werden. Man könnte das zwar in einen Mikroservice auslagern, würde ich in diesem Fall aber eher von abraten. 

**Mögliche Lösungen:**

**The Easy Way**:
1. **Nicos Mailserver verwenden**: Dies ist eine einfache Lösung, da die Einrichtung bereits abgeschlossen ist. Der Nachteil ist jedoch, dass die Reputation möglicherweise nicht optimal ist.
2. **Mailservice verwenden**: Es gibt verschiedene Mail-Dienstleister, die kostenlose Tarife anbieten. Diese können jedoch limitiert sein und die gesendeten Mails könnten Werbung des Mailversenders enthalten. (sendGrid, sendInBlue, Simple Email Service (AWS), GMail, uvm.)
3. **Verwenden der Hochschulmailadresse**: Eine Möglichkeit wäre, die Hochschulmailadresse für den Versand zu verwenden. Dies könnte die Reputation verbessern (Insbesondere für die HS Postfächer). Die Beantragung eines Funktionspostfachs ist grundsätzlich möglich. (Nachfrage zum Thema Sendelimit stellen)

**The Hard Way**:
4. **Eigene Domain und (v)Server kaufen**: Der Kauf einer eigenen Domain und eines (v)Servers würde uns volle Kontrolle über den Mailversand geben. Dies erfordert jedoch eine komplexe Einrichtung und fortlaufende Wartung.

Ich persönlich würde mit Option 3 (Nur mit zusätzlichem Postfach) favorisieren.

**Comment by Danmyrer** [comment]
Wir könnten ja ggf. einen Hochschul-Administrator fragen, ob wir eine Dedizierte Adresse für die Authentifizierung erhalten können. Diese muss auch nicht auf `student.hs-rm.de` enden, aber solange sie nicht von uns gehostet wird, müssen wir uns keine Kosten oder das aufbauen einer E-Mail Reputation (dass die Adresse nicht als Spam markiert wird) kümmern.

**Comment by nicok1** [comment]
Über das ITMZ Ticket System gibt es einen halbwegs standardisierten Weg um ein zusätzliches Postfach zu beantragen.  Das ganze läuft dann ebenfalls über deren Exchange Server und wir könnten darauf mit den gängigen Protokollen zugreifen. (IMAP/POP3) 
Wenn das genehmigt wird, dann wäre schon mal ein wichtiges Problem gelöst. Für erste Tests können wir ja eine Methode "sendMail" im Backend implementieren, die keine Mail versendet, aber eine ausführliche Logausgabe macht.
