### ISSUE TITLE
Tech Stack & Aufgaben

### ISSUE THREAD

**Issue by Danmyrer** [Jacinto-S/VeranstaltungsTauschboerse#6]
Ich würde gerne zusammenfassen, welche Programme wir für das Projekt benutzen und wer was macht, sodass wir mit dem Anlegen der Projektverzeichnisse anfangen können.

| Layer | Tool | Umgebung | Bearbeiter |
| --- | --- | --- | --- |
| DB | Neo4j | Docker | @Danmyrer |
| Geschäftslogik | Springboot | Docker | @nicok1 und @Danmyrer ( DB anbindung ) |
| Backend | Data Processing | Java | @nicok1 und @Jacinto-S (Algorithmen für die Daten fürs Frontend) |
| Frontend | Darstellung | JavasScript | @Luka5W @nicok1 @Jacinto-S (Support)
...

@Luka5W @nicok1 @Jacinto-S  rest bitte ergänzen 😄

**Comment by Jacinto-S** [comment]
Ich kenn mich ja mit den ganzen Technologien und Prozessen nicht so gut aus wie ihr, von daher meine Einträge hier gerne anpassen, wenn da was komisch ist

**Comment by Jacinto-S** [comment]
Ich kenn mich ja mit den ganzen Technologien und Prozessen nicht so gut aus wie ihr, von daher meine Einträge hier gerne anpassen, wenn da was komisch ist

@Luka5W und @nicok1 Ich hab euch mal vorläufig fürs Frontend noch eingetragen weil Lukas das so bisschen angedeutet hat, ändert das Mal so wie es euch passt.

**Comment by nicok1** [comment]
Ich habe mich nochmal beim Backend eingetragen, da ich mich mit Spring Boot auskenne und da auch gut mithelfen kann. Für mich sind Backend und Geschäftslogik eng miteinander verbandelt. Fürs Backend und wie das Frontend möglicherweise bereitgestellt wird, könnt ihr gerne mal in den html-beispiel Branch schauen. 

Aus meiner Sicht sollte alles in einem Repo und Branch entwickelt werden, sofern das Frontend nicht zu komplex wird. (Eigenes großes Framework mit eigenem Tooling usw.) 
Für die Datenbank reicht vermutlich eine Readme oder eine txt mit den Befehlen zum Erzeugen eines Docker Containers. 

Für Features würde dann jeweils ein eigener Branch gestartet werden. Änderungen können dann via Merge Request in den Main Branch übertragen werden. Am Besten sollte nochmal jemand über den Merge Request drüber schauen.

**Comment by Danmyrer** [comment]
@nicok1 in der Beschreibung hab ich mit Backend die Summe aus DB und Geschäftslogik gemeint 😅😅 Passe später die Tabelle entsprechend an
